kind: pipeline
name: puya

steps:
- name: build
  image: python:3
  commands:
  - apt update
  - apt install -y git
  - git submodule update --init --recursive
  - pip install -U https://github.com/OS-Q/pio/archive/main.zip
  - pio platform install file://.
  - pio run -d examples/arduino-blink
  - pio run -d examples/cmsis-blink
  - pio run -d examples/libopencm3-blink
  - pio run -d examples/mbed-serial
  - pio run -d examples/stm32cube-hal-blink
  - pio run -d examples/zephyr-blink

